### ISSUE TITLE
Auth with social providers

### ISSUE THREAD

**Issue by mbalslow** [marmelab/ra-supabase#11]
How would one set up authentication using one of the social providers available in Supabase instead of username/password authentication?

**Comment by braco** [comment]
I'm wondering this too.

This is in the docs at the bottom:
> Add support for third party authentication

Is there a timeline for this?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by fzaninotto** [comment]
oops, sorry I went a big too fast: I thought we were on the react-admin repository!

I'm reopening the issue.

**Comment by mbalslow** [comment]
@fzaninotto I think you can categorize this as a feature request.

**Comment by djhi** [comment]
There's no timeline for this. Feel free to open a PR to implement it

**Comment by mr-bjerre** [comment]
I guess we could add magic link as well (email login links)

**Comment by djhi** [comment]
Implemented in `2.0.0`
