### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by denisprado** [marmelab/ra-supabase#38]
I am looking to any documentation explaining how to use ImageUpload with supabase, but I can´t found.. Do you can help me?

**Comment by slax57** [comment]
ATM we don't have documentation nor code examples for this feature.

You may have more success asking the community, for instance on our [Discord server](https://discord.gg/MR9QFxMc) or on [StackOverflow](https://stackoverflow.com/questions/tagged/supabase).

I'll close this issue since we use Github to track bugs and feature requests only.
